// @generated by script bindgen. Do not edit.
// apiHash: 04efaf3607de11e6

declare global {
  const POEBANE_SCRIPT_API_HASH: string;
  const Input: Poe2InputController;
  function Group(name: string): GroupScope;
  function OnTimer(interval_ms: number): RuleBuilderTimerContext;
  function OnHotkey(gesture: string, scope?: HotkeyScope | null): RuleBuilderHotkeyContext;
  function EnableGroup(name: string): void;
  function DisableGroup(name: string): void;
  function SetAutoStash(enabled: boolean): void;
  function SetAutoFarm(enabled: boolean): void;
  function SetAutoFollow(enabled: boolean): void;
  function SetAutoPickup(enabled: boolean): void;
  function Log(message: string): void;
  function Trace(message: string): void;
  function Debug(message: string): void;
  function Info(message: string): void;
  function Warn(message: string): void;
  function Error(message: string): void;
  function PlayerValid(): boolean;
  function MonsterCount(range?: number | null): number;
  function IsKeyPressed(key: Key): boolean;
  function Random(min: number, max: number): number;
  function PressKey(key: Key): void;
  function HoldKey(key: Key): void;
  function ReleaseKey(key: Key): void;
  function DisplayText(text: string, world_position: Vector3, color?: Color | null): void;
  const World: Poe2WorldState;
  function log(...values: unknown[]): void;
  function trace(...values: unknown[]): void;
  function debug(...values: unknown[]): void;
  function info(...values: unknown[]): void;
  function warn(...values: unknown[]): void;
  function error(...values: unknown[]): void;
  interface Console {
    log(...values: unknown[]): void;
    trace(...values: unknown[]): void;
    debug(...values: unknown[]): void;
    info(...values: unknown[]): void;
    warn(...values: unknown[]): void;
    error(...values: unknown[]): void;
  }
  var console: Console;

  interface Vector2 {
    X: number;
    Y: number;
  }

  interface Vector3 {
    X: number;
    Y: number;
    Z: number;
  }

  interface Vital {
    Current: number;
    Max: number;
    Percent: number;
  }

  interface VitalsInfo {
    HP: Vital;
    ES: Vital;
    Mana: Vital;
    Ward: Vital;
  }

  // A single flask slot (mirrors ReAgent State FlaskInfo). Absent/empty slot ->
  // FlaskInfo::Empty (Active/CanBeUsed false, Charges 0, MaxCharges/ChargesPerUse 1,
  // CanBeUsedIn 100, empty strings).
  interface FlaskInfo {
    Active: boolean;
    CanBeUsed: boolean;
    Charges: number;
    MaxCharges: number;
    ChargesPerUse: number;
    ClassName: string;
    BaseName: string;
    UniqueName: string;
    CanBeUsedIn: number;
    Name: string;
  }

  // The 5-slot PoE2 belt: Flask1/Flask2 = Life/Mana, Charm1/2/3 = charms (all in the
  // one flask server inventory). Numeric indexing is valid only for 0..4; out-of-range
  // integer indexing throws a RangeError at runtime. Flask1 == [0], Flask2 == [1],
  // Charm1 == [2], Charm2 == [3], Charm3 == [4]. Extends the C# FlasksInfo (FlaskCount
  // = 2, no charms) — an owner-directed deviation.
  interface FlasksInfo {
    [index: number]: FlaskInfo;
    Flask1: FlaskInfo;
    Flask2: FlaskInfo;
    Charm1: FlaskInfo;
    Charm2: FlaskInfo;
    Charm3: FlaskInfo;
    Items: FlaskInfo[];
  }

  // A buff / debuff / flask-effect entry (mirrors ReAgent State StatusEffect).
  interface StatusEffect {
    Name: string;
    DisplayName: string;
    Exists: boolean;
    TimeLeft: number;
    TotalTime: number;
    Charges: number;
    FlaskSlot: number;
    PercentTimeLeft: number;
    Skill?: unknown;
  }

  // Buff lookup (mirrors ReAgent State BuffDictionary). Indexing a missing key
  // yields an empty StatusEffect (Exists === false), never null. Has(id) reports
  // presence. Modeled as an intersection so both `Buffs["x"].Exists` and
  // `Buffs.Has("x")` type-check.
  type BuffDictionary = { [id: string]: StatusEffect } & { Has(id: string): boolean };

  interface Entity {
    IsValid: boolean;
    Id: number;
    Address: number;
    Type: string;
    Role: string;
    Path: string;
    Metadata: string;
    PlayerName: string;
    IsAlive: boolean;
    IsTargetable: boolean;
    WorldPosition: Vector3;
    GridPosition: Vector2;
    Vitals: VitalsInfo;
    HP: Vital;
    ES: Vital;
    Mana: Vital;
    Ward: Vital;
  }

  type MouseButton = "Left" | "Middle" | "Right" | "XButton1" | "XButton2";

  // Monster-rarity bit mask seeded on the ReAgent State surface (see SharedRuleStatePrelude).
  const enum MonsterRarity {
    Normal = 1,
    Magic = 2,
    Rare = 4,
    Unique = 8,
    Any = 15,
    AtLeastRare = 12,
  }

  // Stat-id lookup keyed on the ReAgent State surface so `Stats[GameStat.X]`
  // type-checks in the editor.
  const GameStat: Record<string, number>;

  // A LINQ-like wrapped list returned by the ReAgent State `Monsters(...)` helper.
  interface MonsterList {
    length: number;
    Count: number;
    ToVec: Entity[];
    First(predicate?: (entity: Entity) => boolean): Entity;
    FirstOrDefault(predicate?: (entity: Entity) => boolean): Entity | null;
    Any(predicate?: (entity: Entity) => boolean): boolean;
    Where(predicate: (entity: Entity) => boolean): MonsterList;
  }

  // ------------------------------------------------------------------
  // ReAgent State surface (injected by install_native_state; resolved at
  // runtime via the wrapping `with (State)` scope). Declared here so the
  // editor recognizes the bare globals.
  // ------------------------------------------------------------------
  const Vitals: VitalsInfo;
  const Flasks: FlasksInfo;
  const Buffs: BuffDictionary;
  const Skills: Record<string, unknown>;
  const WeaponSwapSkills: Record<string, unknown>;
  const Stats: Record<string, number>;
  const MapStats: Record<string, number>;
  const Ailments: Record<string, unknown>;
  const AreaName: string;
  const IsInHideout: boolean;
  const IsInTown: boolean;
  const IsInPeacefulArea: boolean;
  const IsInEscapeMenu: boolean;
  function Monsters(range?: number | null, rarity?: MonsterRarity | null): MonsterList;
  function MonsterCount(range?: number | null, rarity?: MonsterRarity | null): number;
  function PortalExists(distance?: number | null): boolean;
  // True when seconds since THIS rule last activated >= minTime. A rule that has
  // never activated returns true (elapsed treated as +Infinity).
  function SinceLastActivation(minTime: number): boolean;

  interface Color {
    R: number;
    G: number;
    B: number;
    A: number;
  }

  interface EntityQuery {
    Count: number;
    ToVec: Entity[];
  }

  interface GroupScope {
    name: string;
    Enabled: boolean;
  }

  enum HotkeyScope {
    Window = "Window",
    Global = "Global",
  }

  enum Key {
    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",
    D1 = "D1",
    D2 = "D2",
    D3 = "D3",
    D4 = "D4",
    D5 = "D5",
    Space = "Space",
    Escape = "Escape",
  }

  interface Poe2AreaAccessor {
    IsValid: boolean;
    Current: string | null;
    CurrentAreaLevel: number;
    CurrentAreaHash: number;
    EntitiesCount: number;
    EntityTreeRoot: string;
  }

  interface Poe2CameraAccessor {
    IsViewReady: boolean;
    WorldToScreen(worldPosition: Vector3): Vector2;
    WorldToClient(worldPosition: Vector3): Vector2;
    TryWorldToScreen(worldPosition: Vector3): Vector2 | null;
    TryWorldToClient(worldPosition: Vector3): Vector2 | null;
    ClientToScreen(clientPosition: Vector2): Vector2;
    ScreenToClient(screenPosition: Vector2): Vector2;
  }

  interface Poe2EntitiesAccessor {
    Player: Entity | null;
    Count: number;
    All(limit?: number | null): EntityQuery;
    Monsters(range?: number | null, limit?: number | null): EntityQuery;
    TryGetById(id: number): Entity | null;
  }

  interface Poe2FlasksAccessor {
    Count: number;
    IsAvailable: boolean;
    ServerInventory: ServerInventory | null;
    HasItemAt(index: number): boolean;
    IsActive(index: number): boolean;
    Use(index: number): boolean;
    TryGetServerInventory: ServerInventory | null;
    TryGetItem(index: number): ServerInventorySlotItem | null;
    TryGetSlotClientRect(index: number): RectangleF | null;
  }

  interface Poe2GroundItemInfo {
    EntityId: number;
    EntityAddress: number;
    EntityPath: string;
    LabelAddress: number;
    LabelText: string;
    Name: string;
    IsLootable: boolean;
    IsVisible: boolean;
    CanPickUp: boolean;
    ClientX: number;
    ClientY: number;
    ClientWidth: number;
    ClientHeight: number;
    ClientCenterX: number;
    ClientCenterY: number;
    MatchesName(text: string): boolean;
  }

  interface Poe2InputController {
    IsKeyDown(key: Key): boolean;
    KeyPress(key: Key, keyPressDelay?: number | null): void;
    KeyDown(key: Key): void;
    KeyUp(key: Key): void;
    InputSimulatorLabel: string;
    InputSmootherLabel: string;
    CursorScreenPosition: Vector2;
    CursorClientPosition: Vector2;
    MouseMoveToClient(clientPosition: Vector2): void;
    MouseMoveToClientXY(x: number, y: number): void;
    MouseLeftClickClient(clientPosition: Vector2, clickDelayMs?: number | null): void;
    MouseLeftClickClientXY(x: number, y: number, clickDelayMs?: number | null): void;
    MouseDown(button?: MouseButton | null): void;
    MouseUp(button?: MouseButton | null): void;
  }

  interface Poe2InventoryAccessor {
    IsAvailable: boolean;
    IsOpen: boolean;
    CanClickItems: boolean;
    HasItemAt(x: number, y: number): boolean;
    TryClickItemAt(x: number, y: number): boolean;
    TryCtrlClickItemAt(x: number, y: number): boolean;
    TryClickItemAtWithModifiers(x: number, y: number, control: boolean, shift: boolean): boolean;
    TryGetServerInventory: ServerInventory | null;
    TryClickItem(inventory: ServerInventory, item: ServerInventorySlotItem, control: boolean, shift: boolean, status: Poe2InventoryInteractionStatus): boolean;
    TryGetItemClientClickPoint(inventory: ServerInventory, item: ServerInventorySlotItem, status: Poe2InventoryInteractionStatus): Vector2 | null;
    TryGetItemClientRect(inventory: ServerInventory, item: ServerInventorySlotItem, status: Poe2InventoryInteractionStatus): RectangleF | null;
    TryGetBackpackClientRect: RectangleF | null;
    TryFindItemByAddress(itemAddress: number): unknown | null;
  }

  enum Poe2InventoryInteractionStatus {
    Ready = "Ready",
    InventoryUnavailable = "InventoryUnavailable",
    InventoryNotOpen = "InventoryNotOpen",
    ItemNotFound = "ItemNotFound",
    ItemRectInvalid = "ItemRectInvalid",
    CameraUnavailable = "CameraUnavailable",
    InputFailed = "InputFailed",
  }

  interface Poe2ItemsOnGroundAccessor {
    Count: number;
    VisibleCount: number;
    All(limit?: number | null): Poe2GroundItemInfo[];
    Visible(limit?: number | null): Poe2GroundItemInfo[];
    FirstVisible: Poe2GroundItemInfo | null;
    FindByNameContains(text: string, limit?: number | null): Poe2GroundItemInfo[];
  }

  interface Poe2OsdAccessor {
    DefaultTtlMs: number;
    DefaultTextOutlineColor: Color;
    DefaultTextOutlineThickness: number;
    ActiveItems: number;
    ActiveImGuiRenderers: number;
    AddFloatingTextAtPlayer(text: string, color?: Color | null): void;
    AddFloatingTextAtPlayerWithOutline(text: string, color: Color | null, outline_color: Color, outline_thickness: number): void;
    AddFloatingTextInWorld(position: Vector3, text: string, color?: Color | null): void;
    AddFloatingTextInWorldWithOutline(position: Vector3, text: string, color: Color | null, outline_color: Color, outline_thickness: number): void;
    AddFloatingTextInWorldWithTtl(ttl_ms: number, position: Vector3, text: string, color?: Color | null): void;
    AddFloatingTextInWorldWithTtlAndOutline(ttl_ms: number, position: Vector3, text: string, color: Color | null, outline_color: Color, outline_thickness: number): void;
    AddLineInWorld(start: Vector3, end: Vector3, color: Color, thickness?: number | null): void;
    AddLineInWorldWithTtl(ttl_ms: number, start: Vector3, end: Vector3, color: Color, thickness?: number | null): void;
    Clear(): void;
  }

  interface Poe2PartyAccessor {
    Members: Poe2PartyMemberAccessor[];
  }

  interface Poe2PartyMemberAccessor {
    Index: number;
    Name: string;
    TeleportButton: Element | null;
    HasTeleportButton: boolean;
  }

  interface Poe2ScriptSandbox {
    World: Poe2WorldState;
    Input: Poe2InputController;
    Group(name: string): GroupScope;
    OnTimer(interval_ms: number): RuleBuilderTimerContext;
    OnHotkey(gesture: string, scope?: HotkeyScope | null): RuleBuilderHotkeyContext;
    EnableGroup(name: string): void;
    DisableGroup(name: string): void;
    SetAutoStash(enabled: boolean): void;
    SetAutoFarm(enabled: boolean): void;
    SetAutoFollow(enabled: boolean): void;
    SetAutoPickup(enabled: boolean): void;
    Log(message: string): void;
    Trace(message: string): void;
    Debug(message: string): void;
    Info(message: string): void;
    Warn(message: string): void;
    Error(message: string): void;
    PlayerValid: boolean;
    MonsterCount(range?: number | null): number;
    IsKeyPressed(key: Key): boolean;
    Random(min: number, max: number): number;
    PressKey(key: Key): void;
    HoldKey(key: Key): void;
    ReleaseKey(key: Key): void;
    DisplayText(text: string, world_position: Vector3, color?: Color | null): void;
  }

  interface Poe2StashAccessor {
    IsAvailable: boolean;
    IsOpen: boolean;
    TryGetPanelClientRect: RectangleF | null;
  }

  interface Poe2TradeItem {
    Cell: Element;
    Item: Entity;
    Name: string;
    CellsX: number;
    CellsY: number;
    IsCorrupted: boolean;
  }

  interface Poe2TradeWindow {
    IsOpen: boolean;
    Title: Element | null;
    TitleText: string | null;
    PartnerName: string | null;
    CloseButton: Element | null;
    AcceptButton: Element | null;
    CancelButton: Element | null;
    YourOfferGrid: Element | null;
    TheirOfferGrid: Element | null;
    YourItems: Poe2TradeItem[];
    TheirItems: Poe2TradeItem[];
  }

  interface Poe2UiAccessor {
    RootAddress: number;
    HoverAddress: number;
    HasRoot: boolean;
    HasHover: boolean;
    HasStash: boolean;
    HasInventory: boolean;
    HasGroundLabels: boolean;
    LabelsOnGroundCount: number;
    VisibleLabelsOnGroundCount: number;
    HasParty: boolean;
    HasInvites: boolean;
    Trade: Poe2TradeWindow | null;
  }

  interface Poe2WorldState {
    Area: Poe2AreaAccessor;
    Entities: Poe2EntitiesAccessor;
    Ui: Poe2UiAccessor;
    Party: Poe2PartyAccessor;
    Camera: Poe2CameraAccessor;
    Input: Poe2InputController;
    Flasks: Poe2FlasksAccessor;
    Inventory: Poe2InventoryAccessor;
    ItemsOnGround: Poe2ItemsOnGroundAccessor;
    Osd: Poe2OsdAccessor;
    Stash: Poe2StashAccessor;
    Player: Entity | null;
    ExposedEntityCount: number;
    W2S(worldPosition: Vector3): Vector2;
    TryW2S(worldPosition: Vector3): Vector2 | null;
    W2C(worldPosition: Vector3): Vector2;
    TryW2C(worldPosition: Vector3): Vector2 | null;
  }

  interface RuleBuilderHotkeyContext {
    gesture: string;
    scope: HotkeyScope;
  }

  interface RuleBuilderTimerContext {
    interval_ms: number;
  }

  interface Vector3 {
    X: number;
    Y: number;
    Z: number;
  }

}

export {};
